options:
  machineType: 'N1_HIGHCPU_8'
  service_account: 'sarath-research-py@appspot.gserviceaccount.com'
  logsBucket: 'gs://my-build-logs-bucket'

steps:
  - name: 'gcr.io/cloud-builders/python'
    args: ['pip', 'install', '-r', 'requirements.txt']
  - name: 'gcr.io/cloud-builders/python'
    args: ['python', 'manage.py', 'test']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
