steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
logsBucket: 'gs://sarathgcpbucket'
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sarath-research-py/my-django-app:$COMMIT_SHA', '.']
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sarath-research-py/my-django-app:$COMMIT_SHA']
  # Deploy the Docker image to Google Kubernetes Engine
  #- name: 'gcr.io/cloud-builders/kubectl'
   # args:
     # - 'set'
     # - 'image'
     # - 'deployment/my-django-app'
     # - 'my-django-app=gcr.io/sarath-research-py/my-django-app:$COMMIT_SHA'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
  secretEnv:
  - 'GCLOUD_SERVICE_KEY'
